server:
  port: 7778
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh, env, bus-env
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
